server:
  port: 8081

spring:
  application:
    name: SportCcenter
  datasource:
    url: jdbc:mysql://localhost:3306/sportscenter
    username: root
    password: as0976377178
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect